import styles from "../../styles/Home.module.css";
import Head from "next/head";
import HeaderComponent from "../../components/Header";
import LoginComponent from "../../components/Login";
import FooterComponent from "../../components/Footer";
import ScrollComponent from "../../components/Scroll";

export default function Login() {
    return (
        <div className={styles.container}>

            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <HeaderComponent/>

            <LoginComponent/>

            <FooterComponent/>

            <ScrollComponent />

        </div>
    )
}
