import Head from 'next/head'
import HeaderComponent from '../components/Header'
import FooterComponent from '../components/Footer'
import HomeComponent from '../components/Home'
import ScrollComponent from '../components/Scroll'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
       
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeaderComponent />

      <HomeComponent />

      <FooterComponent />

      <ScrollComponent />

    </div>
  )
}
